require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventsUsersController do

  # This should return the minimal set of attributes required to create a valid
  # EventsUser. As you add validations to EventsUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventsUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all events_users as @events_users" do
      events_user = EventsUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:events_users).should eq([events_user])
    end
  end

  describe "GET show" do
    it "assigns the requested events_user as @events_user" do
      events_user = EventsUser.create! valid_attributes
      get :show, {:id => events_user.to_param}, valid_session
      assigns(:events_user).should eq(events_user)
    end
  end

  describe "GET new" do
    it "assigns a new events_user as @events_user" do
      get :new, {}, valid_session
      assigns(:events_user).should be_a_new(EventsUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested events_user as @events_user" do
      events_user = EventsUser.create! valid_attributes
      get :edit, {:id => events_user.to_param}, valid_session
      assigns(:events_user).should eq(events_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventsUser" do
        expect {
          post :create, {:events_user => valid_attributes}, valid_session
        }.to change(EventsUser, :count).by(1)
      end

      it "assigns a newly created events_user as @events_user" do
        post :create, {:events_user => valid_attributes}, valid_session
        assigns(:events_user).should be_a(EventsUser)
        assigns(:events_user).should be_persisted
      end

      it "redirects to the created events_user" do
        post :create, {:events_user => valid_attributes}, valid_session
        response.should redirect_to(EventsUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved events_user as @events_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventsUser.any_instance.stub(:save).and_return(false)
        post :create, {:events_user => {}}, valid_session
        assigns(:events_user).should be_a_new(EventsUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventsUser.any_instance.stub(:save).and_return(false)
        post :create, {:events_user => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested events_user" do
        events_user = EventsUser.create! valid_attributes
        # Assuming there are no other events_users in the database, this
        # specifies that the EventsUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EventsUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => events_user.to_param, :events_user => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested events_user as @events_user" do
        events_user = EventsUser.create! valid_attributes
        put :update, {:id => events_user.to_param, :events_user => valid_attributes}, valid_session
        assigns(:events_user).should eq(events_user)
      end

      it "redirects to the events_user" do
        events_user = EventsUser.create! valid_attributes
        put :update, {:id => events_user.to_param, :events_user => valid_attributes}, valid_session
        response.should redirect_to(events_user)
      end
    end

    describe "with invalid params" do
      it "assigns the events_user as @events_user" do
        events_user = EventsUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventsUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => events_user.to_param, :events_user => {}}, valid_session
        assigns(:events_user).should eq(events_user)
      end

      it "re-renders the 'edit' template" do
        events_user = EventsUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventsUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => events_user.to_param, :events_user => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested events_user" do
      events_user = EventsUser.create! valid_attributes
      expect {
        delete :destroy, {:id => events_user.to_param}, valid_session
      }.to change(EventsUser, :count).by(-1)
    end

    it "redirects to the events_users list" do
      events_user = EventsUser.create! valid_attributes
      delete :destroy, {:id => events_user.to_param}, valid_session
      response.should redirect_to(events_users_url)
    end
  end

end
